parameters:
  kubernetes:
    control:
      configmap:
        opencontrail-config:
          version: ${_param:contrail_config_config_version}
          pillar:
            opencontrail:
              config:
                multi_tenancy: false
                identity:
                  engine: none
                  password: none
                  token: none
                  host: none
                database:
                  members:
                  - host: ${_param:opencontrail_database_service_host01}
                    port: 9160
                ifmap:
                  members:
                  - user: ctl01
                    password: ctl01
      service:
        contrail-config:
          enabled: true
          service: opencontrail
          namespace: default
          cluster: opencontrail
          hostNetwork: True
          affinity:
            anti_affinity:
              name: podAntiAffinity
              expression:
                label_selector:
                  name: labelSelector
                  selectors:
                  - key: app
                    value: opencontrail-config
              topology_key: kubernetes.io/hostname
          ports:
          - port: 8082
            name: api
          - port: 5998
            name: discovery
          - port: 8443
            name: ifmap
          role: config
          type: LoadBalancer
          kind: Deployment
          apiVersion: extensions/v1beta1
          replicas: ${_param:opencontrail_replicas}
          image_pull_secretes: tcpcloud
          cluster_ip: ${_param:opencontrail_config_service_host}
          nodeSelector:
          - key: controller
            value: control
          container:
            contrail-config:
              image: ${_param:opencontrail_docker_config}
              tag: ${_param:opencontrail_docker_config_tag}
              image_pull_policy: Always
              ports:
              - port: 8082
                name: api
              - port: 5998
                name: discovery
              - port: 8443
                name: ifmap
              command:
              - /entrypoint.sh
              - config
              variables:
              - name: IP
                fieldPath: status.podIP
              - name: LOCAL_IP
                fieldPath: status.podIP
              - name: HOST_HOSTNAME
                fieldPath: spec.nodeName
              volumes:
              - name: opencontrail-config
                mount: /etc/ifmap-server/publisher.properties
                read_only: True
                sub_path: publisher.properties
              - name: opencontrail-config
                mount: /etc/ifmap-server/log4j.properties
                read_only: True
                sub_path: log4j.properties
              - name: opencontrail-config
                mount: /etc/ifmap-server/basicauthusers.properties
                read_only: True
                sub_path: basicauthusers.properties
              - name: opencontrail-config
                mount: /etc/contrail/contrail-api.conf
                read_only: True
                sub_path: contrail-api.conf
              - name: opencontrail-config
                mount: /etc/contrail/contrail-discovery.conf
                read_only: True
                sub_path: contrail-discovery.conf
              - name: opencontrail-config
                mount: /etc/contrail/vnc_api_lib.ini
                read_only: True
                sub_path: vnc-api-lib.ini
              - name: opencontrail-config
                mount: /etc/contrail/contrail-device-manager.conf
                read_only: True
                sub_path: contrail-device-manager.conf
              - name: opencontrail-config
                mount: /etc/sudoers.d/contrail_sudoers
                read_only: True
                sub_path: contrail-sudoers
              - name: opencontrail-config
                mount: /etc/contrail/contrail-schema.conf
                read_only: True
                sub_path: contrail-schema.conf
              - name: opencontrail-config
                mount: /etc/contrail/contrail-svc-monitor.conf
                read_only: True
                sub_path: contrail-svc-monitor.conf
              - name: opencontrail-config
                mount: /etc/contrail/supervisord_config_files/contrail-config-nodemgr.ini
                read_only: True
                sub_path: contrail-config-nodemgr.ini
          volume:
            opencontrail-config:
              version: ${_param:contrail_config_config_version}
              type: config_map
              item:
                publisher:
                  key: publisher.properties
                  path: publisher.properties
                log4j:
                  key: log4j.properties
                  path: log4j.properties
                basicauthusers:
                  key: basicauthusers.properties
                  path: basicauthusers.properties
                api:
                  key: contrail-api.conf
                  path: contrail-api.conf
                vnc:
                  key: vnc-api-lib.ini
                  path: vnc-api-lib.ini
                device:
                  key: contrail-device-manager.conf
                  path: contrail-device-manager.conf
                schema:
                  key: contrail-schema.conf
                  path: contrail-schema.conf
                svc:
                  key: contrail-svc-monitor.conf
                  path: contrail-svc-monitor.conf
                nodemgr:
                  key: contrail-config-nodemgr.ini
                  path: contrail-config-nodemgr.ini
                discovery:
                  key: contrail-discovery.conf
                  path: contrail-discovery.conf
                sudoers:
                  key: contrail-sudoers
                  path: contrail-sudoers
